version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 3.3
  build:
    commands:
      ## ------ Install Packages
      - cd $CODEBUILD_SRC_DIR
      - cd generator/ruby
      - bundle install 
      - bundle exec rake generate 
  post_build:
    commands:
      - aws s3 cp "$CODEBUILD_SRC_DIR/public/index.html"  "s3://$WWWDOMAIN/index.html"
      - aws s3 cp "$CODEBUILD_SRC_DIR/public/style.css"  "s3://$WWWDOMAIN/style.css"
      - aws s3 cp "$CODEBUILD_SRC_DIR/public/assets/"  "s3://$WWWDOMAIN/assets/" --recursive
      - aws s3 cp "$CODEBUILD_SRC_DIR/public/assets/"  "s3://$SUBDOMAIN/assets/" --recursive

      # Check if projects_assets exists before copying
      - if [ -d "$CODEBUILD_SRC_DIR/public/projects_assets" ]; then aws s3 cp "$CODEBUILD_SRC_DIR/public/projects_assets/"  "s3://$SUBDOMAIN/project_assets/" --recursive; else echo "Skipping projects_assets upload, directory does not exist."; fi

      # Check if projects exists before copying
      - if [ -d "$CODEBUILD_SRC_DIR/public/projects" ]; then aws s3 cp "$CODEBUILD_SRC_DIR/public/projects/"  "s3://$SUBDOMAIN/projects/" --recursive; else echo "Skipping projects upload, directory does not exist."; fi
