AWSTemplateFormatVersion: "2010-09-09"
Description: Build Server
Parameters:
  WWWDomain:
    Type: String
  SubDomain:
    Type: String
  GitHubRepo:
    Type: String
Resources:
  CodeBuildServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'codebuild.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'CodeBuildServiceRolePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:ListObjectsV2'
                Resource:
                  - !Sub arn:aws:s3:::${WWWDomain}
                  - !Sub arn:aws:s3:::${WWWDomain}/* 
                  - !Sub arn:aws:s3:::${SubDomain}
                  - !Sub arn:aws:s3:::${SubDomain}/*
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      TimeoutInMinutes: 10
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER 
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0 
        EnvironmentVariables:
          - Name: WWWDOMAIN
            Type: PLAINTEXT
            Value: !Ref WWWDomain
          - Name: SUBDOMAIN
            Type: PLAINTEXT
            Value: !Ref SubDomain
      Source:
        Auth:
          Resource:
            Fn::ImportValue: credsCodeBuildSourceCredentialArn
          Type: OAUTH
        Type: GITHUB  
        Location: !Ref GitHubRepo 
        GitCloneDepth: 1
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: refs/heads/prod
