AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Secrets Manager to Store GitHub Personal Access Token  
Parameters:
  SecretName:
    Type: String
    Default: codebuildpat
    Description: "The secret name that will contain the personal Access Token"
Resources: 
 Secret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: codebuildpat
      Description: "This secret has a dynamically generated secret password."
      SecretString: '{"token":"replacement"}'

Outputs:
  SecretName:
    Description: SecretName
    Value: !Ref SecretName
    Export:
        Name: !Sub ${AWS::StackName}SecretName
